# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jtc-v1pfEOyl3GwyhUKFtFmWggfba2e1
"""

import numpy as np
import pandas as p
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

data=pd.read_csv('/content/spam.csv')
data

data.columns

data.info()

data.isna().sum()

data['Spam']=data['Category'].apply(lambda x:1 if x=='spam' else 0)
data.head(5)

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(data.Message,data.Spam,test_size=0.25)

#CounterVectorizer Convert the text into matrics
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.naive_bayes import MultinomialNB

from sklearn.pipeline import Pipeline
clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

clf.fit(X_train,y_train)

emails=[
    'Sounds great! Are you home now?',
    'Will u meet ur dream partner soon? Is ur career off 2 a flyng start? 2 find out free, txt HORO followed by ur star sign, e. g. HORO ARIES'
]

clf.predict(emails)

clf.score(X_test,y_test)

"""**Explanation**

Spam mail detection involves identifying and filtering out unwanted and unsolicited emails, commonly known as spam, from legitimate emails. This process uses various techniques and algorithms to determine whether an email is spam. Here's a detailed overview of the key concepts and techniques involved in spam mail detection:

### Key Concepts in Spam Detection

1. **Features of Spam Emails**:
   - **Content-Based Features**: Keywords, phrases, and unusual text patterns often found in spam emails.
   - **Header-Based Features**: Information in the email headers, such as the sender’s email address, IP address, and routing information.
   - **Behavioral Features**: Patterns in sending frequency, email volumes, and recipient lists.

2. **Techniques and Algorithms**:
   - **Rule-Based Filtering**: Uses predefined rules and heuristics to identify spam. For example, if an email contains certain words or phrases, it is marked as spam.
   - **Bayesian Filtering**: A probabilistic approach that uses Bayes' theorem to calculate the probability that an email is spam based on its content.
   - **Machine Learning Algorithms**:
     - **Supervised Learning**: Algorithms such as Support Vector Machines (SVM), Decision Trees, Random Forests, and Neural Networks. These models are trained on labeled datasets where emails are marked as 'spam' or 'not spam'.
     - **Unsupervised Learning**: Techniques like clustering and anomaly detection to identify spam without labeled training data.
   - **Blacklisting and Whitelisting**: Maintaining lists of known spam sources (blacklists) and trusted senders (whitelists).

3. **Common Steps in Spam Detection**:
   - **Data Collection**: Gathering a dataset of emails, including both spam and legitimate emails.
   - **Preprocessing**: Cleaning and preparing the data, which involves tokenizing text, removing stopwords, stemming or lemmatization, and feature extraction.
   - **Model Training**: Using the preprocessed data to train a machine learning model. For supervised learning, this involves splitting the data into training and testing sets.
   - **Model Evaluation**: Assessing the model's performance using metrics such as accuracy, precision, recall, F1-score, and ROC-AUC curve.
   - **Deployment**: Integrating the trained model into an email system to classify incoming emails in real-time.

### Example Workflow

1. **Data Collection**:
   - Collect a dataset of emails, such as the Enron email dataset or other publicly available email datasets.
   
2. **Preprocessing**:
   - Tokenize the email content.
   - Remove stopwords (common words that do not carry significant meaning, like "and", "the", etc.).
   - Apply stemming or lemmatization to reduce words to their base forms.
   - Extract features such as term frequency-inverse document frequency (TF-IDF).

3. **Model Training**:
   - Choose a machine learning algorithm, such as a Naive Bayes classifier.
   - Train the model on a labeled dataset.
   
4. **Model Evaluation**:
   - Evaluate the model using a test set.
   - Calculate performance metrics.

5. **Deployment**:
   - Implement the model in an email client or server.
   - Continuously monitor and update the model to handle new spam techniques.
"""